-- PostgreSQL schema generated from MongoDB (Mongoose) models in `be/src/models/*`.
-- Target: PostgreSQL 13+.
--
-- Mapping notes:
-- - Mongo `ObjectId` is mapped to `BIGINT GENERATED BY DEFAULT AS IDENTITY`.
-- - Mongo `Mixed` / `Record<string, unknown>` is mapped to `JSONB`.
-- - Mongo string arrays are mapped to `TEXT[]`.
-- - Embedded arrays are normalized into child tables.
--
-- Run this on a fresh database. If you need re-run, drop objects first.

BEGIN;

-- ---- Enums (from Mongo schema enums) ----
CREATE TYPE role_enum AS ENUM ('customer', 'staff', 'admin');
CREATE TYPE voucher_discount_type_enum AS ENUM ('percentage', 'fixed_amount');
CREATE TYPE payment_method_enum AS ENUM ('cod', 'banking', 'momo', 'vnpay', 'zalopay');
CREATE TYPE zalopay_channel_enum AS ENUM ('gateway', 'wallet', 'bank_card', 'atm');
CREATE TYPE payment_status_enum AS ENUM ('pending', 'paid', 'failed', 'refunded');
CREATE TYPE order_status_enum AS ENUM (
  'awaiting_payment',
  'pending',
  'confirmed',
  'shipping',
  'delivered',
  'completed',
  'cancelled',
  'returned'
);
CREATE TYPE return_request_status_enum AS ENUM ('pending', 'approved', 'rejected', 'refunded');
CREATE TYPE cancel_refund_request_status_enum AS ENUM ('pending', 'rejected', 'refunded');
CREATE TYPE refund_method_enum AS ENUM ('bank_transfer', 'wallet');
CREATE TYPE inventory_reason_enum AS ENUM ('import', 'sale', 'return', 'adjustment', 'damage');
CREATE TYPE comment_target_model_enum AS ENUM ('product');

-- ---- Users ----
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  full_name TEXT,
  phone TEXT,
  role role_enum NOT NULL DEFAULT 'customer',
  avatar_url TEXT,
  staff_start_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---- Address ---- (Mongo timestamps: false)
CREATE TABLE addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label TEXT NOT NULL DEFAULT 'Home',
  recipient_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  street TEXT NOT NULL,
  city TEXT NOT NULL,
  district TEXT NOT NULL,
  ward TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX addresses_user_id_is_default_idx ON addresses(user_id, is_default);

-- ---- Master data ----
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX categories_name_idx ON categories(name);

CREATE TABLE brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX brands_name_idx ON brands(name);
CREATE INDEX brands_is_active_idx ON brands(is_active);

CREATE TABLE colors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  hex_code TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT colors_hex_code_format_chk
    CHECK (hex_code IS NULL OR hex_code ~ '^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$')
);
CREATE INDEX colors_name_idx ON colors(name);
CREATE INDEX colors_is_active_idx ON colors(is_active);

CREATE TABLE sizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX sizes_name_idx ON sizes(name);
CREATE INDEX sizes_is_active_idx ON sizes(is_active);

-- ---- Product ----
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category_id BIGINT NOT NULL REFERENCES categories(id),
  brand_id BIGINT REFERENCES brands(id),
  brand TEXT NOT NULL DEFAULT 'Generic',
  description TEXT,
  attributes JSONB,
  images TEXT[] NOT NULL DEFAULT '{}',
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  average_rating NUMERIC(3,2) NOT NULL DEFAULT 0,
  review_count INTEGER NOT NULL DEFAULT 0,
  sold_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT products_average_rating_range_chk CHECK (average_rating >= 0 AND average_rating <= 5),
  CONSTRAINT products_review_count_nonneg_chk CHECK (review_count >= 0),
  CONSTRAINT products_sold_count_nonneg_chk CHECK (sold_count >= 0)
);
CREATE INDEX products_category_available_idx ON products(category_id, is_available);
CREATE INDEX products_brand_id_available_idx ON products(brand_id, is_available);
CREATE INDEX products_brand_available_idx ON products(brand, is_available);

-- ---- Product variant ----
CREATE TABLE product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  color_id BIGINT REFERENCES colors(id),
  size_id BIGINT REFERENCES sizes(id),
  sku TEXT NOT NULL UNIQUE,
  size TEXT NOT NULL DEFAULT 'Standard',
  price BIGINT NOT NULL,
  original_price BIGINT,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  images TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT product_variants_price_nonneg_chk CHECK (price >= 0),
  CONSTRAINT product_variants_original_price_nonneg_chk CHECK (original_price IS NULL OR original_price >= 0),
  CONSTRAINT product_variants_stock_quantity_nonneg_chk CHECK (stock_quantity >= 0)
);

-- Mongo unique index { productId, colorId, size } without sparse:
-- enforce uniqueness even when color_id is NULL.
CREATE UNIQUE INDEX product_variants_uq_product_color_size
  ON product_variants(product_id, color_id, size)
  WHERE color_id IS NOT NULL;
CREATE UNIQUE INDEX product_variants_uq_product_size_when_no_color
  ON product_variants(product_id, size)
  WHERE color_id IS NULL;

CREATE INDEX product_variants_product_available_idx ON product_variants(product_id, is_available);
CREATE INDEX product_variants_size_id_idx ON product_variants(size_id);

-- ---- Inventory log ----
CREATE TABLE inventory_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id),
  variant_id BIGINT REFERENCES product_variants(id),
  change_amount INTEGER NOT NULL,
  reason inventory_reason_enum NOT NULL,
  performed_by BIGINT NOT NULL REFERENCES users(id),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX inventory_logs_product_created_idx ON inventory_logs(product_id, created_at DESC);

-- ---- Cart ---- (Mongo timestamps: { createdAt: false, updatedAt: true })
CREATE TABLE carts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Mongo cartItemSchema has _id: false => use composite PK in SQL.
CREATE TABLE cart_items (
  cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  variant_id BIGINT NOT NULL REFERENCES product_variants(id),
  quantity INTEGER NOT NULL DEFAULT 1,
  selected_attributes JSONB,
  PRIMARY KEY (cart_id, variant_id),
  CONSTRAINT cart_items_quantity_positive_chk CHECK (quantity >= 1)
);
CREATE INDEX cart_items_product_id_idx ON cart_items(product_id);

-- ---- Voucher ----
CREATE TABLE vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  description TEXT,
  discount_type voucher_discount_type_enum NOT NULL,
  discount_value BIGINT NOT NULL,
  min_order_value BIGINT NOT NULL DEFAULT 0,
  max_discount_amount BIGINT,
  start_date TIMESTAMPTZ NOT NULL,
  expiration_date TIMESTAMPTZ NOT NULL,
  usage_limit INTEGER NOT NULL,
  max_usage_per_user INTEGER NOT NULL,
  used_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT vouchers_discount_value_nonneg_chk CHECK (discount_value >= 0),
  CONSTRAINT vouchers_min_order_value_nonneg_chk CHECK (min_order_value >= 0),
  CONSTRAINT vouchers_max_discount_amount_nonneg_chk CHECK (max_discount_amount IS NULL OR max_discount_amount >= 0),
  CONSTRAINT vouchers_usage_limit_nonneg_chk CHECK (usage_limit >= 0),
  CONSTRAINT vouchers_max_usage_per_user_positive_chk CHECK (max_usage_per_user >= 1),
  CONSTRAINT vouchers_used_count_nonneg_chk CHECK (used_count >= 0)
);

-- ---- Orders ----
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code TEXT NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  shipping_recipient_name TEXT NOT NULL,
  shipping_phone TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  subtotal BIGINT NOT NULL,
  shipping_fee BIGINT NOT NULL DEFAULT 0,
  discount_amount BIGINT NOT NULL DEFAULT 0,
  total_amount BIGINT NOT NULL,
  payment_method payment_method_enum NOT NULL DEFAULT 'cod',
  zalopay_channel zalopay_channel_enum,
  payment_status payment_status_enum NOT NULL DEFAULT 'pending',
  payment_txn_ref TEXT UNIQUE,
  payment_transaction_no TEXT,
  payment_gateway_response_code TEXT,
  paid_at TIMESTAMPTZ,
  refunded_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  voucher_id BIGINT REFERENCES vouchers(id),
  status order_status_enum NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT orders_subtotal_nonneg_chk CHECK (subtotal >= 0),
  CONSTRAINT orders_shipping_fee_nonneg_chk CHECK (shipping_fee >= 0),
  CONSTRAINT orders_discount_amount_nonneg_chk CHECK (discount_amount >= 0),
  CONSTRAINT orders_total_amount_nonneg_chk CHECK (total_amount >= 0)
);
CREATE INDEX orders_user_created_idx ON orders(user_id, created_at DESC);
CREATE INDEX orders_status_created_idx ON orders(status, created_at DESC);

CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  product_name TEXT NOT NULL,
  variant_id BIGINT NOT NULL REFERENCES product_variants(id),
  variant_sku TEXT NOT NULL,
  variant_color TEXT NOT NULL,
  product_image TEXT,
  quantity INTEGER NOT NULL,
  price BIGINT NOT NULL,
  total BIGINT NOT NULL,
  CONSTRAINT order_items_quantity_positive_chk CHECK (quantity >= 1),
  CONSTRAINT order_items_price_nonneg_chk CHECK (price >= 0),
  CONSTRAINT order_items_total_nonneg_chk CHECK (total >= 0)
);
CREATE INDEX order_items_order_id_idx ON order_items(order_id);

CREATE TABLE order_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status order_status_enum NOT NULL,
  changed_by BIGINT NOT NULL REFERENCES users(id),
  note TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX order_status_history_order_changed_idx ON order_status_history(order_id, changed_at DESC);

-- Embedded array: returnRequests (OrderReturnRequest) + items
CREATE TABLE order_return_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  requested_by BIGINT NOT NULL REFERENCES users(id),
  status return_request_status_enum NOT NULL DEFAULT 'pending',
  refund_method refund_method_enum NOT NULL DEFAULT 'bank_transfer',
  refund_amount BIGINT NOT NULL,
  reason TEXT,
  note TEXT,
  refund_evidence_images TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT order_return_requests_refund_amount_nonneg_chk CHECK (refund_amount >= 0)
);
CREATE INDEX order_return_requests_order_id_idx ON order_return_requests(order_id);

CREATE TABLE order_return_request_items (
  return_request_id BIGINT NOT NULL REFERENCES order_return_requests(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  product_name TEXT NOT NULL,
  variant_id BIGINT NOT NULL REFERENCES product_variants(id),
  variant_sku TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price BIGINT NOT NULL,
  total BIGINT NOT NULL,
  PRIMARY KEY (return_request_id, variant_id),
  CONSTRAINT order_return_request_items_quantity_positive_chk CHECK (quantity >= 1),
  CONSTRAINT order_return_request_items_price_nonneg_chk CHECK (price >= 0),
  CONSTRAINT order_return_request_items_total_nonneg_chk CHECK (total >= 0)
);

-- Embedded object: cancelRefundRequest (one per order)
CREATE TABLE order_cancel_refund_requests (
  order_id BIGINT PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
  requested_by BIGINT NOT NULL REFERENCES users(id),
  status cancel_refund_request_status_enum NOT NULL DEFAULT 'pending',
  refund_amount BIGINT NOT NULL,
  bank_code TEXT NOT NULL,
  bank_name TEXT NOT NULL,
  account_number TEXT NOT NULL,
  account_holder TEXT NOT NULL,
  note TEXT,
  admin_note TEXT,
  refund_evidence_images TEXT[] NOT NULL DEFAULT '{}',
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  processed_by BIGINT REFERENCES users(id),
  CONSTRAINT order_cancel_refund_requests_refund_amount_nonneg_chk CHECK (refund_amount >= 0)
);
CREATE INDEX order_cancel_refund_requests_status_idx ON order_cancel_refund_requests(status);

-- ---- Review ----
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  order_id BIGINT NOT NULL REFERENCES orders(id),
  rating SMALLINT NOT NULL,
  content TEXT,
  images TEXT[] NOT NULL DEFAULT '{}',
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  reply_content TEXT,
  replied_at TIMESTAMPTZ,
  replied_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reviews_rating_range_chk CHECK (rating >= 1 AND rating <= 5),
  CONSTRAINT reviews_order_product_uq UNIQUE (order_id, product_id)
);
CREATE INDEX reviews_product_created_idx ON reviews(product_id, created_at DESC);

-- ---- Comment ---- (polymorphic target; currently only `product`)
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_id BIGINT NOT NULL,
  target_model comment_target_model_enum NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(id),
  content TEXT NOT NULL,
  parent_id BIGINT REFERENCES comments(id),
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX comments_target_idx ON comments(target_model, target_id, created_at DESC);

-- ---- Chat support ----
CREATE TABLE chat_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'support',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  customer_id BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX chat_conversations_updated_idx ON chat_conversations(updated_at DESC);

-- Mongo participantIds: ObjectId[] -> join table
CREATE TABLE chat_conversation_participants (
  conversation_id BIGINT NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX chat_conversation_participants_user_idx ON chat_conversation_participants(user_id);

CREATE TABLE chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES users(id),
  content TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX chat_messages_conversation_created_idx ON chat_messages(conversation_id, created_at DESC);

-- Mongo readBy: ObjectId[] -> join table
CREATE TABLE chat_message_read_by (
  message_id BIGINT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (message_id, user_id)
);

-- ---- Chatbot presets ----
CREATE TABLE chatbot_presets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX chatbot_presets_active_sort_updated_idx
  ON chatbot_presets(is_active, sort_order, updated_at DESC);
CREATE INDEX chatbot_presets_question_idx ON chatbot_presets(question);

-- Mongo productIds: ObjectId[] -> join table
CREATE TABLE chatbot_preset_products (
  preset_id BIGINT NOT NULL REFERENCES chatbot_presets(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  PRIMARY KEY (preset_id, product_id)
);

-- ---- Push subscriptions ----
CREATE TABLE push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role role_enum NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  expiration_time BIGINT,
  key_p256dh TEXT NOT NULL,
  key_auth TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX push_subscriptions_user_role_idx ON push_subscriptions(user_id, role);
CREATE INDEX push_subscriptions_role_idx ON push_subscriptions(role);

COMMIT;
